version: '3'

services:
  web:
    image: ghcr.io/mzrimsek/resume-site:latest
    container_name: resume_site
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resume_frontend.rule=${TRAEFIK_HOST_RULE}"
      - "traefik.http.routers.resume_frontend.entrypoints=websecure"
      - "traefik.http.routers.resume_frontend.tls.certresolver=tlsresolver"
      - "traefik.http.services.resume_frontend.loadbalancer.server.port=3000"
    restart: unless-stopped
    
networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}