version: '2'

services:
  web:
    image: ghcr.io/mzrimsek/resume-site:latest
    container_name: resume_site
    ports:
      - ${HOST_PORT}:3000
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=${TRAEFIK_HOST_RULE}"
      - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${HOST_PORT}"
    restart: unless-stopped
    
networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}