# Services
apiVersion: v1
kind: Service
metadata:
  name: resume
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      name: frontend
      port: 3000

# Deployments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: resume
  labels:
    app: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mzrimsek/resume-site:latest
          ports:
            - name: frontend
              containerPort: 3000

# Routes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: resume
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${PROXY_URL}`)
      kind: Rule
      services:
        - name: resume
          namespace: default
          port: 3000
  tls:
    certResolver: tlsresolver
